import {
  HammerIcon,
  AcademicCapIcon,
  NotebookIcon,
  PaletteIcon,
  MeditationIcon,
  GlobusIcon,
  CodeIcon,
  ChiefHatIcon,
  ThermometrIcon,
  StarRainbowIcon,
  ConfettiIcon,
  ShareCircleIcon,
  MusicNoteIcon,
  ShakehandIcon,
  LeafIcon,
  MasksIcon,
  RulePencilIcon,
  PaletteCardsIcon,
  GarageIcon,
  DialogBulbIcon,
  HeartPlusIcon,
  MirrorIcon,
  PerfumeIcon,
  DumbbellIcon,
} from '@ui/Icons';

export const characteristics = [
  {
    id: 'health',
    position: { x: 300, y: 200 },
    name: 'Здоровье',
    dedcription: '',
    color: 'red',
    icon: <HeartPlusIcon color="red900" />,
    sorceHandle: 'bottom',
    targetHandle: 'top',
    branches: [
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 340, y: 60 },
        name: 'Физическое здоровье',
        id: 'physical_health',
        icon: <ThermometrIcon color="red900" />,
      },
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 260, y: 60 },
        name: 'Ментальное здоровье',
        id: 'mental_health',
        icon: <MeditationIcon color="red900" />,
      },
    ],
  },
  {
    sorceHandle: 'right',
    targetHandle: 'left',
    id: 'art',
    position: { x: 200, y: 250 },
    name: 'Искусство',
    dedcription: '',
    color: 'green',
    icon: <StarRainbowIcon color="green900" />,
    branches: [
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 240, y: 150 },
        name: 'Изобразительное искусство',
        id: 'fine_arts',
        icon: <PaletteIcon color="green900" />,
      },
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 160, y: 160 },
        name: 'Прикладное искусство',
        id: 'applied_arts',
        icon: <PaletteCardsIcon color="green900" />,
      },
      {
        sorceHandle: 'right',
        targetHandle: 'left',
        position: { x: 100, y: 200 },
        name: 'Исполнительское искусство',
        id: 'performing_arts',
        icon: <MusicNoteIcon color="green900" />,
      },
      {
        sorceHandle: 'right',
        targetHandle: 'left',
        position: { x: 120, y: 280 },
        name: 'Культура',
        id: 'culture',
        icon: <NotebookIcon color="green900" />,
      },
    ],
  },
  {
    sorceHandle: 'right',
    targetHandle: 'left',
    position: { x: 210, y: 360 },
    id: 'social',
    name: 'Социализация',
    dedcription: '',
    color: 'orange',
    icon: <ShakehandIcon color="orange900" />,
    branches: [
      {
        sorceHandle: 'right',
        targetHandle: 'left',
        position: { x: 120, y: 370 },
        name: 'Развлечения',
        icon: <ConfettiIcon color="orange900" />,
        id: 'fun',
      },
      {
        sorceHandle: 'top',
        targetHandle: 'left',
        position: { x: 140, y: 440 },
        name: 'Связи',
        icon: <ShareCircleIcon color="orange900" />,
        id: 'networking',
      },
      {
        sorceHandle: 'top',
        targetHandle: 'bottom',
        position: { x: 210, y: 460 },
        name: 'Общение',
        icon: <DialogBulbIcon color="orange900" />,
        id: 'communication',
      },
    ],
  },
  {
    sorceHandle: 'top',
    targetHandle: 'bottom',
    position: { x: 300, y: 400 },
    id: 'beauty',
    name: 'Красота',
    dedcription: '',
    color: 'violet',
    icon: <MirrorIcon color="violet900" />,
    branches: [
      {
        sorceHandle: 'top',
        targetHandle: 'bottom',
        position: { x: 260, y: 540 },
        name: 'Тело',
        icon: <DumbbellIcon color="violet900" />,
        id: 'body',
      },
      {
        sorceHandle: 'top',
        targetHandle: 'bottom',
        position: { x: 340, y: 540 },
        name: 'Эстетика',
        icon: <PerfumeIcon color="violet900" />,
        id: 'aethetic',
      },
    ],
  },

  {
    sorceHandle: 'left',
    targetHandle: 'right',
    id: 'science',
    position: { x: 400, y: 350 },
    name: 'Науки',
    dedcription: '',
    color: 'blue',
    icon: <AcademicCapIcon color="blue900" />,
    branches: [
      {
        sorceHandle: 'left',
        targetHandle: 'right',
        position: { x: 400, y: 500 },
        name: 'Гуманитарные науки',
        icon: <MasksIcon color="blue900" />,
        id: 'human_science',
      },
      {
        sorceHandle: 'left',
        targetHandle: 'right',
        position: { x: 500, y: 450 },
        name: 'Технические науки',
        icon: <CodeIcon color="blue900" />,
        id: 'technical_science',
      },
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 550, y: 350 },
        name: 'Иностранные языки',
        icon: <GlobusIcon color="blue900" />,
        id: 'languages',
      },
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 500, y: 300 },
        name: 'Эрудиция',
        icon: <RulePencilIcon color="blue900" />,
        id: 'erudition',
      },
    ],
  },
  {
    sorceHandle: 'left',
    targetHandle: 'right',
    position: { x: 400, y: 250 },
    id: 'household',
    name: 'Хозяйство',
    dedcription: '',
    color: 'yellow',
    icon: <GarageIcon color="yellow900" />,
    branches: [
      {
        sorceHandle: 'left',
        targetHandle: 'right',
        position: { x: 550, y: 250 },
        name: 'Собирательство',
        icon: <LeafIcon color="yellow900" />,
        id: 'foraging',
      },
      {
        sorceHandle: 'left',
        targetHandle: 'right',
        position: { x: 500, y: 150 },
        name: 'Кулинария',
        icon: <ChiefHatIcon color="yellow900" />,
        id: 'culinary',
      },
      {
        sorceHandle: 'bottom',
        targetHandle: 'top',
        position: { x: 400, y: 150 },
        name: 'Домашнее хозяйство',
        icon: <HammerIcon color="yellow900" />,
        id: 'homekeeping',
      },
    ],
  },
];
